language: node_js
node_js:
- '4.0'
- '5.0'
- '6.0'
- '7.0'
cache: yarn
after_success:
  - npm run build
before_deploy:
  - cd dist
deploy:
  provider: npm
  email: brian@serverless.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: serverless/fdk
